<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        //$this->load->model('login_model');
        $this->load->model('admin_model');
        $this->load->model('member_model');
    }

    public function index()
    {   
        
        if(!$this->input->post()) //jika tidak ada input data post maka akan ke halaman login
        {
            $this->load->view('login');
        }
        else
        {

            $cek_login_adm = $this->admin_model->cek_login_adm(
                $this->input->post('username'),
                $this->input->post('password')
                );
            $cek_login_member = $this->member_model->cek_login_member(
                $this->input->post('username'),
                $this->input->post('password')
                );
            if(!empty($cek_login_adm))
            {
                $this->session->set_userdata('username',$cek_login_adm->username);

                $this->session->set_userdata('logined',true);               
                redirect("home/setting");

            }
            else if(!empty($cek_login_member))
            {
                $this->session->set_userdata('username',$cek_login_member->email);
                $this->session->set_userdata('id_member',$cek_login_member->id_member);
                $this->session->set_userdata('logined',true);               
                redirect("home/loginUser");
            }
            else 
            {
                redirect("home/login");
            }

        }
        
    } 
    
    public function logout()
    {
        $this->session->unset_userdata('logined');//hapus session userdata
        redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */